# Generated by Django 2.1 on 2018-08-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_number', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('special_shipping', models.IntegerField(default=0)),
                ('paypal_code', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens', models.CharField(max_length=100)),
                ('focal_length', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=200)),
                ('nominal_format', models.CharField(max_length=200)),
                ('max_coverage', models.CharField(max_length=200)),
                ('intended_camera', models.CharField(max_length=200)),
                ('camera_class', models.CharField(max_length=200)),
                ('mount', models.CharField(max_length=200)),
                ('flange_distance', models.CharField(max_length=200)),
                ('rear_element', models.CharField(max_length=200)),
                ('lens_kit_no', models.IntegerField(default=0)),
                ('focus_unit', models.CharField(max_length=200)),
                ('shutter_plate', models.CharField(max_length=200)),
                ('front_spacer', models.CharField(max_length=200)),
                ('barrel_length', models.CharField(max_length=200)),
                ('rs_20', models.CharField(max_length=200)),
                ('rs_30', models.CharField(max_length=200)),
                ('rs_40', models.CharField(max_length=200)),
                ('rs_60', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
                ('filter_size', models.CharField(max_length=200)),
                ('shutter', models.CharField(max_length=200)),
                ('image_circle', models.CharField(max_length=200)),
                ('fov_35mm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='System_lens_135',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_system', models.CharField(max_length=100)),
                ('shutter', models.CharField(max_length=100)),
                ('merc_body', models.CharField(max_length=200)),
                ('merc_body2', models.CharField(default='none', max_length=100)),
                ('shutter_spacer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System_lens_medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_system', models.CharField(max_length=100)),
                ('shutter', models.CharField(max_length=100)),
                ('shutter2', models.CharField(default='none', max_length=100)),
                ('shutter3', models.CharField(default='none', max_length=100)),
                ('bolt_length', models.CharField(max_length=100)),
                ('bolt_length2', models.CharField(default='none', max_length=100)),
                ('bolt_length3', models.CharField(default='none', max_length=100)),
                ('washers', models.CharField(max_length=100)),
                ('washers2', models.CharField(default='none', max_length=100)),
                ('washers3', models.CharField(default='none', max_length=100)),
                ('front_spacer', models.CharField(max_length=100)),
                ('front_spacer2', models.CharField(default='none', max_length=100)),
                ('front_spacer3', models.CharField(default='none', max_length=100)),
                ('spacer_ring', models.CharField(max_length=100)),
                ('spacer_ring2', models.CharField(default='none', max_length=100)),
                ('spacer_ring3', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
