# Generated by Django 2.0.6 on 2018-08-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_auto_20180816_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='lens_kit_no',
            field=models.CharField(max_length=50),
        ),
    ]
